#!/bin/bash

MY_NETWORK="10.0.0.0/24"

# Replace the ip address here with the ip address for your computer. You can use the programs "/sbin/ifconfig", or "/sbin/ip addr show". 
MY_HOST="10.0.0.3"

# Network interfaces
IN=enp0s3
OUT=enp0s3

# Path to iptables, "/usr/sbin/iptables"
IPTABLES="/usr/sbin/iptables"
IPTABLES_RESTORE="/usr/sbin/iptables-restore"
IPSET="/usr/sbin/ipset"

########################
### DON'T TOUCH THIS ###
########################
#This purposefully restablishes the firewall to a known ruleset.
#If you change it make sure you have tested it before
#You can generate such a ruleset with iptables-save

#This is generated by iptables-save and allows applying multiple
#rules in a single row
$IPTABLES_RESTORE <<EOF
*filter

#$IPTABLES -N LAB_NET
:LAB_NET - [0:0]
-A LAB_NET -s 10.0.0.0/24 -j RETURN
-A LAB_NET -j RETURN

#$IPTABLES -N LOG_DROP
:LOG_DROP - [0:0]
#$IPTABLES -A LOG_DROP -j LOG --log-prefix "iptables-dropped: " --log-level debug
-A LOG_DROP -j LOG --log-prefix "iptables-dropped: " --log-level 7
#$IPTABLES -A LOG_DROP -j DROP
-A LOG_DROP -j DROP

#$IPTABLES -P INPUT DROP
:INPUT DROP [0:0]
#Xmas scan and NULL scan block
-A INPUT -p tcp --tcp-flags ALL NONE -j DROP
-A INPUT -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP

#Limit ping rate
-A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT
#log all ping that exceeded limit
-A INPUT -p icmp --icmp-type echo-request -j LOG_DROP

#For loopback communication, allow internal communicate
-A INPUT -i lo -j ACCEPT

#Keep current ETABLISHED connection
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#Allow services
#SSHD
-A INPUT -p tcp --dport 22 -j ACCEPT
#APACHE
-A INPUT -p tcp --dport 8080 -j ACCEPT
#RPCBIND
-A INPUT -p tcp --dport 111 -j ACCEPT
-A INPUT -p udp --dport 111 -j ACCEPT

#Spoofing block
-A INPUT -s 172.16.0.0/12 -j DROP
-A INPUT -s 192.168.0.0/16 -j DROP
-A INPUT -s 169.254.0.0/16 -j DROP

#Deny but still accept lab net
-A INPUT -s 10.0.0.0/8 -j LAB_NET
#-A INPUT -s 10.0.0.1 -j ACCEPT

#LOG all not matched
-A INPUT -j LOG_DROP

#Here you could add your own rules if you wanted
#
#$IPTABLES -P FORWARD DROP
:FORWARD DROP [0:0]
#Here you could add your own rules if you wanted
#
#$IPTABLES -P OUTPUT ACCEPT
:OUTPUT ACCEPT [0:0]
-A OUTPUT -o lo -j ACCEPT
#Here you could add your own rules if you wanted
#
COMMIT
EOF

##################
### START HERE ###
#################
#You can also add your rules to the ruleset you saw above but it may be
#easier for you to begin here. Notice how on the ruleset above, the
#rules are always preceded by the commented command that caused them
#This is not necessary but is there to serve you as reference.

echo "Done!"
